### ISSUE TITLE
process

### ISSUE THREAD

**Issue by XFivezzz** [yeerwen/UniSeg#11]
![image](https://github.com/yeerwen/UniSeg/assets/93257077/c181c30c-4913-46d3-a39d-8d5f1ce7254d)
![image](https://github.com/yeerwen/UniSeg/assets/93257077/f8b41d51-77a5-4f90-a66b-3ecfc133cf66)
我已经跑过你这个模型verse20的plan_and_preprocess，我想把预处理后的数据应用到其它模型，所以，这个模型预处理生成之后的文件是和nnunetv1的一模一样的吗？比如说这个DoDNetPlans_plans_3D是不是和nnUNetPlansv2.1_plans_3D一样

**Comment by XFivezzz** [comment]
There is also the question of why there is no seg array in the preprocessed npz file
![image](https://github.com/yeerwen/UniSeg/assets/93257077/e5d56d89-faf3-45ff-836e-81a0c274f604)

**Comment by yeerwen** [comment]
> ![image](https://user-images.githubusercontent.com/93257077/258271303-c181c30c-4913-46d3-a39d-8d5f1ce7254d.png) ![image](https://user-images.githubusercontent.com/93257077/258271339-f8b41d51-77a5-4f90-a66b-3ecfc133cf66.png) 我已经跑过你这个模型verse20的plan_and_preprocess，我想把预处理后的数据应用到其它模型，所以，这个模型预处理生成之后的文件是和nnunetv1的一模一样的吗？比如说这个DoDNetPlans_plans_3D是不是和nnUNetPlansv2.1_plans_3D一样

可以的，你可以直接将DoDNetPlans_plans_3D改名为nnUNetPlansv2.1_plans_3D，就可以在nnunet v1上进行运行了。需要注意的是我们直接设置了重采样的spacing，而不是采用nnUNet预处理中自动生成的spacing。

对于第二个问题：npz文件中是image和label合并在一起的数据。你可以通过输出data的形状来确定。

**Comment by XFivezzz** [comment]
感谢你的回复，我明白了，v1版本是合并在一起的，v2是data和seg分开的

**Comment by Myrrolinz** [comment]
Hi，我和你有同样的问题，但是我在data conversion部分就出现问题了（程序莫名其妙就卡着动不了了）。我可以请求您share一份copy吗？非常感谢您的帮助！如果您能指导我完成data conversion的话，不胜感激！

**Comment by yeerwen** [comment]
卡住了一般是内存爆了导致的，建议关注一下内存的变化。整个数据集处理完的在200多G，实在不方便传输。建议还是按照我提供的流程下载公开的数据集，允许预处理代码。

**Comment by Myrrolinz** [comment]
> 卡住了一般是内存爆了导致的，建议关注一下内存的变化。整个数据集处理完的在200多G，实在不方便传输。建议还是按照我提供的流程下载公开的数据集，允许预处理代码。

我换了3090+15核CPU后成功了，非常感谢您的解答！
