### ISSUE TITLE
Why is the number of test num is 0

### ISSUE THREAD

**Issue by XFivezzz** [yeerwen/UniSeg#12]
![3987e1392dc97052dfa0d2eb1ec71fc](https://github.com/yeerwen/UniSeg/assets/93257077/139bfb3c-7cf6-45e1-b4b6-1bae25285ec9)
When I apply the v1 preprocessed model to the new model, I find that Verse20's test is 0Is this normal？

**Comment by yeerwen** [comment]
Our study does not incorporate any test data, as we are specifically working with datasets for which labels are readily available. Therefore, there is no test data included in our research.

**Comment by XFivezzz** [comment]
Thanks for your reply. One more question: Among the 11 datasets in upstream, do all single-task models also use data preprocessed by nnunetv1？
![image](https://github.com/yeerwen/UniSeg/assets/93257077/f12f3cb6-9df8-4818-af8c-dc27be1303c5)

**Comment by yeerwen** [comment]
We use the same data preprocessing on all datasets for both single-task models and universal models.
