### ISSUE TITLE
Train on my own 2d data

### ISSUE THREAD

**Issue by JtaoC** [yeerwen/UniSeg#13]
Hello, I want to ask how to train upstream model on my own 2d data. I've tried to convert my own dataset to nnunet dataset. But it seems that I failed.

**Comment by yeerwen** [comment]
Sorry, I haven't experimented with training a 2D task using the nnUNet framework. I suggest you first familiarize yourself with training a 2D task within the nnUNet framework. With that foundation, it will be easier for you to modify our code, which is specifically designed for 3D tasks, to accommodate 2D inputs.

**Comment by JtaoC** [comment]
> Sorry, I haven't experimented with training a 2D task using the nnUNet framework. I suggest you first familiarize yourself with training a 2D task within the nnUNet framework. With that foundation, it will be easier for you to modify our code, which is specifically designed for 3D tasks, to accommodate 2D inputs.

Thanks very much for your reply, I will try your suggestion.
