### ISSUE TITLE
"plans.pkl" seems to be missing

### ISSUE THREAD

**Issue by chenluda** [yeerwen/UniSeg#19]
Thanks for your excellent work!

Due to limited computing resources, I would like to use the pre-trained model to inference directly, but I found that the supporting "plans.pkl" seems to be missing, can you release it if convenient?

Thanks again!

**Comment by yeerwen** [comment]
Hi, you can get the 'plans.pkl' here. 
![image](https://github.com/yeerwen/UniSeg/assets/108005335/4b0daf85-0b73-41cb-8377-8739df4591dd)

**Comment by yeerwen** [comment]
Hi, I have uploaded a download link for this file in the "README" file.

**Comment by chenluda** [comment]
Thank you, "Luck Anything" ! @yeerwen
