### ISSUE TITLE
output channel 

### ISSUE THREAD

**Issue by kimsekeun** [yeerwen/UniSeg#20]
Thanks for great work.

"Note that the channel number of multi-scale segmentation maps is set to the maximum number of classes among all tasks."
it means that for output channel of decoder, it set to 3 (organ ,tumor, vertebra) ?
If I understand correctly the final output channel is 3 for all datasets?

<img width="867" alt="Screenshot 2023-12-02 at 4 34 42 PM" src="https://github.com/yeerwen/UniSeg/assets/11817202/b3c81f84-9dc0-44fa-8dd9-d96ebc8296e1">

**Comment by yeerwen** [comment]
The number of output channels is set to 4 as it also includes the background class.

**Comment by yeerwen** [comment]
The channel number aligns with the maximum number of classes among all tasks and does not correspond to the organ, tumor, and vertebra.

**Comment by kimsekeun** [comment]
To clarify the classes and task, classes includes organ list and task means dataset A, B, C or is it ( MR, CT ...)?

e.g. dataset A : liver kidney hepatic         colon spleen 
       dataset B : liver                           lung 

1. is output channel considered as 6 + 1 (background). and tasks is 2 (dataset A, B). is that correct ? 
2. I think MOTS have 7 classes at least, but how did you set as 4 in paper?
3. When calculating loss, for example in dataset B, if output channel is 7 then how you calculate loss in class that is not annotated in dataset b? 

thank you in advance.

**Comment by yeerwen** [comment]
Q1: Task is 2 (A and B), output channel 5 (class number of A) + 1 (background).
Q2: See Q1.
Q3: Ignoring the output channels corresponding to the classes that are not annotated in dataset b.
