### ISSUE TITLE
How long is the total training time?

### ISSUE THREAD

**Issue by Myrrolinz** [yeerwen/UniSeg#23]
Hi! Hope everything is fine with you!

I'd like to train your model from scratch, but I feel training is a really long process. I've already trained for 3 days. I wonder how long is the total training time? (Upstream and Downstream, respectively). I'm using RTX 2080 ti (11G).

btw, happy new year :)

**Comment by yeerwen** [comment]
Training the UniSeg model on the RTX 2080 Ti requires approximately four days for completing the upstream task (11 sub-tasks). Each downstream task takes about 3.5 hours to train.

**Comment by Myrrolinz** [comment]
thank you for your reply!
