### ISSUE TITLE
inference and evaluation question

### ISSUE THREAD

**Issue by Myrrolinz** [yeerwen/UniSeg#24]
Hi, I have two questions :)

1. In `run_ssl.sh`，there is only `nnUNet_train`, no `nnUNet_predict`. So how do I run inference? Will the `nnUNet_train` order  automatically do the inference task?

2. I noticed you only provide `UniSeg_Metrics_test.py` on Upstream task. Is there a downstream version? How can I evaluate on downstream task?

really appreciate your help! looking forward to your reply.

**Comment by yeerwen** [comment]
Q1: Indeed, the nnUNet_train process includes the inference phase immediately following the end of the training phase.
Q2: We directly follow the nnUNet's evaluation procedure.

**Comment by Myrrolinz** [comment]
> Q1: Indeed, the nnUNet_train process includes the inference phase immediately following the end of the training phase. Q2: We directly follow the nnUNet's evaluation procedure.

I see. Thank you!
