### ISSUE TITLE
MICCAI SegRap 2023 fine-tune weight and preprocessing release

### ISSUE THREAD

**Issue by ding3820** [yeerwen/UniSeg#26]
Hi, 

Thanks for open-souring the amazing work. I am wondering if you can release the fine-tuning weight and preprocessing of your second place solution in [MICCAI SegRap 2023](https://segrap2023.grand-challenge.org/final-ranking/)? Thanks.

**Comment by yeerwen** [comment]
Certainly. Here is the download link: https://drive.google.com/file/d/1fZY3EBwGK70Du9S-RYn9wUMsz99HJ89S/view?usp=sharing. Please don't hesitate to reach out if there's anything I can assist you with.

**Comment by ding3820** [comment]
Hi @yeerwen,

Thank you for your fast respond. I've briefly looked into your submitted codes. I have a few questions and hope you could help me clear out. 

* I was actually trying to find a SOTA model that could segment brain OARs. I happened to find MICCAI SegRap 2023 challenge and your work apparently had the best open-source repository. I am wondering if I can simply adopt your work at the challenge and generate OARs for my ncCT files? I figure that UniSeg model in this challenge is powerful enough to segment all the OARs I need but with only ncCT input.
* In the submitted implementation, I see `nnunet/network_architecture/PromptNet.py` which is actually different from this repo's [implementation](https://github.com/yeerwen/UniSeg/blob/main/Upstream/nnunet/network_architecture/Prompt_generic_UNet.py). It seems that you didn't use any prompt method as reported in UniSeg and it is actually more like a simple UNet. Did this model perform the best in the challenge?

Hope I can get back from you soon. Thanks for your time.

**Comment by yeerwen** [comment]
Hi,

Two insightful questions!
Q1: For the SegRap 2023 challenge, the models were indeed trained using two types of input images: ncCT and cCT. Based on this, if you wish to adapt the model to work exclusively with ncCT inputs, it would be necessary to re-train the model following UniSeg's downstream training procedure.
Q2: Regarding the SegRap challenge, it is designed as a single-task competition. We leveraged UniSeg through a fine-tuning approach, which allows us to utilize the robust representation capabilities that were developed from training on upstream datasets. Consequently, the nnunet/network_architecture/PromptNet.py employed for the challenge remains unchanged and can be found [here](https://github.com/yeerwen/UniSeg/blob/main/Downstream/nnunet/network_architecture/PromptNet.py).
