### ISSUE TITLE
Question about comparison study

### ISSUE THREAD

**Issue by Younger330** [yeerwen/UniSeg#27]
Hello,

I noticed that you have a universal model named CLIP DoDnet. Does this involve creating a text representation for each dataset and then inputting it into the CLIP model, with other settings similar to DODnet?

**Comment by yeerwen** [comment]
Yes.

**Comment by yeerwen** [comment]
Embeddings derived from CLIP are integrated following the procedures used in the [CLIP-Driven Universal Model](https://github.com/ljwztc/CLIP-Driven-Universal-Model).

**Comment by Younger330** [comment]
> Yes.

 If I understand correctly, there is only one prompt for a dataset, am I right?

**Comment by yeerwen** [comment]
It's true.
