### ISSUE TITLE
pred shape error

### ISSUE THREAD

**Issue by sharonlee12** [yeerwen/UniSeg#29]
Traceback (most recent call last):
  File "UniSeg_Metrics_test.py", line 115, in <module>
    evaluation(root, i)
  File "UniSeg_Metrics_test.py", line 78, in evaluation
    assert label.shape == pred.shape, [label.shape, pred.shape]
AssertionError: [(512, 512, 60), (498, 498, 300)]

**Comment by sharonlee12** [comment]
Does anyone meet this problem？Hope to reveive reply!

**Comment by yeerwen** [comment]
Your prediction should match the original ground truth, not the resampled version.
