### ISSUE TITLE
Question for Run sh run_ssl.sh for training 

### ISSUE THREAD

**Issue by jucyLL** [yeerwen/UniSeg#3]
Thank you for your excellent work. How do I train the uniseg please? nnUNet_train: error: unrecognized arguments: -exp_name UniSeg_Trainer

**Comment by yeerwen** [comment]
Did you do this step "Copy Upstream/nnunet to replace nnunet, which is installed by pip install nnunet (the address is usually 'anaconda3/envs/ your envs/lib/python3.8/site-packages/nnunet')."

**Comment by jucyLL** [comment]
Thank you for your reply, it solved my problem.
