### ISSUE TITLE
Test dataset to evaluate upstream models

### ISSUE THREAD

**Issue by YYinn** [yeerwen/UniSeg#4]
Thank you for your excellent work. I finished the training phase of upstream task and was trying to evaluate those models. But I noticed that all the pkl files created by Convert_XX_to_nnUNet_dataset contain empty 'test' dictionary. According to the Tab. 1 in paper, how can i find the test dataset of those upstream tasks? Thank you!

**Comment by yeerwen** [comment]
Actually, for each dataset, we use its validation data as the test data to evaluate the model's performance.  To avoid test data (validation data) leaking, we use the checkpoint from the last iteration as the final checkpoint and do not use any post-processing in nnUNet.

**Comment by YYinn** [comment]
Thank you!
