### ISSUE TITLE
How to inference unlabelled data

### ISSUE THREAD

**Issue by angolin22** [yeerwen/UniSeg#5]
Thanks for your work, this helps me a lot, so I want to ask some question. 
1. May I ask how to use the model trained on 11 upstream datasets to inference unlabeled data?
2. When I use the model trained on 11 upstream datasets to predict and inference unlabeled data, could I obtain the labels of all organs, tumors and vertebrae in these 11 upstream datasets?

**Comment by yeerwen** [comment]
For Q1: We didn't consider the inference of unlabeled data for the last version code. If you want to do it, there are some necessary modifications to our code. Specifically, you need to concern about the code of nnUNet_predict in the nnUNet framework and allow the framework to know the ongoing task. Thanks for your reminder, we will provide the above code in tomorrow.
For Q2: No, our UniSeg can only predict all targets of a specific task in one iteration when batch size is set to 1.

**Comment by yeerwen** [comment]
For Q1: We didn't consider the inference of the new data in the latest version of our code. If you want to do so, there are some necessary changes that need to be made to our code. Specifically, you need to concern the code of nnUNet_predict in the nnUNet framework to let the framework know the ongoing task. Thanks for your reminder, we will implement the above functionality and provide the code tomorrow.

For Q2: No, our UniSeg can only predict all targets for a specific task in one iteration when the batch size is set to 1.

**Comment by angolin22** [comment]
Thanks very much for your reply. I want to ask: when predicting, how do I set up the prediction for a specific task or where is this part of the code?

**Comment by yeerwen** [comment]
We are implementing this part of the code.

**Comment by yeerwen** [comment]
Hi, we have updated the code and 'README' file to implement this function

**Comment by yeerwen** [comment]
Hi, we have uploaded this part of the code.
