### ISSUE TITLE
Verse2020 dataset

### ISSUE THREAD

**Issue by XFivezzz** [yeerwen/UniSeg#7]
when I am running Python Convert in this step_ VerSe20_ To_ NnUNet_ Dataset. py  has been stuck as shown in the picture and has not generated splits_ Final.pkl file
![image](https://github.com/yeerwen/UniSeg/assets/93257077/6a2c0792-41f8-4c22-af0b-4904b159c3b1)

**Comment by yeerwen** [comment]
Maybe you can check the CPU and memory utilization. In my experience, this process takes longer due to the large data scale. One more question, how long has the program been stuck roughly?

**Comment by XFivezzz** [comment]
Thank you, you're right. I replaced a GPU and it's not stuck here anymore, but I feel like it will take a long time to complete it

> Maybe you can check the CPU and memory utilization. In my experience, this process takes longer due to the large data scale. One more question, how long has the program been stuck roughly?

**Comment by yeerwen** [comment]
For the preprocessing of VerSe20, we use the code provided in the nnUNet framework. Thank you for your suggestion, GPU can really speed up the process.
